[package]
name = "rusty-reloader"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
notify = "5.1.0"
clap = "4.1.4"
serde = { version = "1", features = ["derive"] }
serde_json = "1.0"
